services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unit_converter_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/app/core/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - unit_converter_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: unit_converter_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - unit_converter_net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  unit_converter_net:
    driver: bridge

volumes:
  redis_data: